name: PR title
description: 'Github action to enforce naming convention on pull request title'

inputs:
  regex:
    description: 'The regular expression to validate the pull request title against'
    required: false
    default: '^(feature|bugfix|hotfix|custom):\s.*'

  min_length:
    description: 'Min length of title'
    required: false
    default: '1'

runs:
  using: 'node12'
  main: './scripts/validate-pull-request-title.js'
