name: Install dependencies

on:
  workflow_call:
    inputs:
      config:
        required: true
        type: string
      test:
        type: string
        required: false

jobs:
  install-dependencies:
    runs-on: ubuntu-latest

    steps:
      - shell: bash
        run: echo "${{ toJSON(inputs) }}"


      - name: '⚙️ Set env variables'
        uses: actions/github-script@v7
        with:
          script: |
            const inputs = ${{ toJSON(inputs) }}
            console.log(inputs);
#            const v = ${{ inputs.config }};
#            console.log('Config123', v);
#            console.log(typeof(v));
#            Object.entries(${{ inputs.config }}).forEach(([name, value]) => {
#              core.exportVariable(name, value);
#            });

#      - name: '☁️ Checkout repository'
#        uses: actions/checkout@v3
#
#      - name: '🔧 Setup Node.js v.${{ env.NODE_VERSION }}'
#        uses: actions/setup-node@v3
#        with:
#          node-version: ${{ matrix.node-version }}
#          cache: 'npm'
#
#      - name: '🔍 Restore node_modules from cache'
#        uses: actions/cache@v3
#        id: cache-node-modules
#        with:
#          path: node_modules
#          key: ${{ env.NODE_MODULES_CACHE_KEY }}
#          restore-keys: ${{ env.NODE_MODULES_CACHE_RESTORE_KEY }}
#
#      - name: '📦 Install dependencies'
#        if: steps.cache-node-modules.outputs.cache-hit != 'true'
#        run: npm ci
