name: PR workflow

on:
  pull_request:
    # Run the workflow when we want to merge changes into these branches
    branches: ["master", "develop", "feature/*"]
    # Events to which the workflow will respond
    types: [opened, synchronize]

jobs:
#  lint:
#    uses: ./.github/workflows/linter.yml
#
#  unit-tests:
#    needs: [ lint ]
#    uses: ./.github/workflows/unit-tests.yml

  build:
#    needs: [ lint, unit-tests ]
    uses: ./.github/workflows/build.yml

  deploy-to-firebase:
    needs: [ build ]
    steps:
      - uses: ./.github/workflows/firebase-hosting-pull-request.yml
