name: Pull Request Title
description: Validates the pull request title against a regular expression

inputs:
  regex:
    description: 'The regular expression to validate the pull request title against'
    required: true
    default: '^(feature|bugfix|hotfix|custom):\s.*'

  min_length:
    description: 'Min length of title'
    required: false
    default: '1'

runs:
  using: 'node12'
  main: './scripts/validate-pull-request-title.js'
