name: PR workflow

on:
  pull_request:
    # Run the workflow when we want to merge changes into these branches
    branches: [ "master", "develop", "feature/*" ]

jobs:
  lint:
    uses: ./.github/workflows/linter.yml

  unit_tests:
    needs: [ lint ]
    uses: ./.github/workflows/unit-tests.yml

  build:
    needs: [ lint, unit_tests ]
    uses: ./.github/workflows/build.yml
