name: PR workflow

on:
  pull_request:
    branches: [ "master", "develop", "feature/*" ] # run workflow when we want to merge changes into these branches

jobs:
  pr-workflow:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: lint
        uses: ./.github/workflows/linter.yml

      - name: unit_tests
        needs: [ lint ]
        uses: ./.github/workflows/unit-tests.yml

      - name: build
        needs: [ lint, unit_tests ]
        uses: ./.github/workflows/build.yml
