name: PR workflow

on:
  pull_request:
    # Run the workflow when we want to merge changes into these branches
    branches: ['master', 'develop', 'feature/*']
    # Events to which the workflow will respond
    types: [opened, synchronize]

jobs:
  setup-config:
    uses: ./.github/workflows/config.yml

  install-dependencies:
    needs: [setup-config]
    uses: ./.github/workflows/install-dependencies.yml
    with:
      config: ${{ needs.setup-config.outputs.shared-variables }}

#  lint:
#    uses: ./.github/workflows/linter.yml
#
#  circular-dependencies:
#    uses: ./.github/workflows/circular-dependencies.yml
#
#  unit-tests:
#    uses: ./.github/workflows/unit-tests.yml
#
#  build:
#    needs: [lint, unit-tests]
#    uses: ./.github/workflows/build.yml
#
#  deploy-to-firebase:
#    needs: [build]
#    uses: ./.github/workflows/firebase-hosting-pull-request.yml
#    secrets:
#      firebaseServiceAccountSecret: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_ANGULAR_GITHUB_ACTIONS_388812 }}
